### ISSUE TITLE
Sync command makes configure.sh hang on HPC system

### ISSUE THREAD

**Issue by uwefladrich** [ecmwf/ecbundle#10]
### What happened?

[Sorry to report as "Bug Report" event though it is not necessarily a bug. There is no other appropriate issue template.]

The `ecbundle-build` "hangs" on our HPC system at this stage:
```
[...]
DATE: 2024-04-17T08:47:40Z

+ SOURCE_DIR=[...]/openifs48r1/source
+ INSTALL_DIR=[...]/openifs48r1/install
+ BUILD_DIR=[...]/openifs48r1/build
+ BUILD_TYPE=BIT 
```
No process is active (i.e. non-sleeping) after this happens and no progress over a long time (at least 10 minutes) for no apparent reason.

### What are the steps to reproduce the bug?

Any `bundle.yml` will do. Running `ecbundle-build`  (after `ecbundle-create`) will trigger the issue on our machine.

It turns out that `ecbundle-create` hangs in the `configure.sh` script. In particular, `configure.sh` calls the `sync` command as part of the `trace_off` alias:

https://github.com/ecmwf/ecbundle/blob/814873bf2c770b2693b08181243dd05d110e0c2c/ecbundle/build.py#L143

I suspected that running `sync` on an HPC with large/many filesystems could have the effect of stalling the process in non-active state. As a test, I removed `sync` from the alias and that solved the hanging issue.

I think that `configure.sh` should not call `sync`, at least not without arguments. Maybe it should only sync `$LOG_FILE`, which is probably the intention.

### Version

2.1.1

### Platform (OS and architecture)

Rocky Linux 9.3 (Blue Onyx)

### Organisation

SMHI/EC-Earth

**Comment by wdeconinck** [comment]
Hi @uwefladrich that is a very good observation. I think we can indeed just add the $LOG_FILE as argument, and hopefully that also fixes the hang you experience.

**Comment by wdeconinck** [comment]
Thanks both for this ! This is now merged in `develop` branch.
